apiVersion: v1
kind: Service
metadata:
  labels:
    app: bot-nodeport
  name: bot-nodeport
spec:
  ports:
    - name: 'bot-svc'
      nodePort: 30080
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: bot-nodeport
  type: NodePort
